application: giewiki-hrd
version: 1-18-3
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /scripts
  static_dir: scripts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /index.xml
  script: index.py

- url: /build_tag_index
  script: build_tag_index.py

- url: /dynamic/iewiki-xsl
  script: dynamic-xsl.py

- url: /dynamic/js/.*
  script: dynamic-xsl.py

- url: /every_1_hours
  script: every_hour.py

- url: /upload
  script: UploadHandler.application

- url: /.*
  script: iewiki.application
